# -*- coding: utf-8 -*-
"""Olympic Python Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQWaF24UfLwag3-_DTLp5aWM1oQ2fufy

DATA COLLECTION
"""

# Import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler, MinMaxScaler, RobustScalerxaX

# Load the dataset
df = pd.read_csv("athlete_events.csv")

# Display first few rows
print("Dataset Preview:")
print(df.head())

# Check dataset structure and data types
print("\nDataset Information:")
print(df.info())

"""DATA CLEANING AND TRANSFORMATION"""

# Check for missing values
print("\nMissing Values Count:")
print(df.isnull().sum())

# Identify columns with missing values
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]
print("Missing Values per Column:\n", missing_values)

# Impute numerical columns with median
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
imputer_num = SimpleImputer(strategy="median")
df[num_cols] = imputer_num.fit_transform(df[num_cols])

# Impute categorical columns with most frequent value (mode)
cat_cols = df.select_dtypes(include=['object']).columns
imputer_cat = SimpleImputer(strategy="most_frequent")
df[cat_cols] = imputer_cat.fit_transform(df[cat_cols])

# Verify missing values are handled
print("\nMissing values after imputation:\n", df.isnull().sum())

"""Exploratory Data Analysis (EDA)"""

# Summary statistics
print("\nSummary Statistics:")
print(df.describe())

# Outlier detection using box plots
plt.figure(figsize=(12,6))
sns.boxplot(data=df[num_cols])
plt.title("Boxplot for Outlier Detection")
plt.xticks(rotation=90)
plt.show()

# Outlier removal using IQR
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

# Define upper and lower bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Remove outliers
df_no_outliers = df[~((df[num_cols] < lower_bound) | (df[num_cols] > upper_bound)).any(axis=1)]
print("Shape before outlier removal:", df.shape)
print("Shape after outlier removal:", df_no_outliers.shape)

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for seaborn
sns.set(style="whitegrid")

# Create subplots for Age, Height, and Weight distributions
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Age distribution
sns.histplot(df["Age"].dropna(), bins=30, kde=True, ax=axes[0], color="blue")
axes[0].set_title("Age Distribution")

# Height distribution
sns.histplot(df["Height"].dropna(), bins=30, kde=True, ax=axes[1], color="green")
axes[1].set_title("Height Distribution")

# Weight distribution
sns.histplot(df["Weight"].dropna(), bins=30, kde=True, ax=axes[2], color="red")
axes[2].set_title("Weight Distribution")

plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x=df['Age'], y=df['Weight'], alpha=0.5)
plt.title("Age vs. Weight")
plt.xlabel("Age")
plt.ylabel("Weight")
plt.show()

# Scatter plot for Height vs. Weight with trend line
plt.figure(figsize=(8, 6))
sns.scatterplot(x=df["Height"], y=df["Weight"], alpha=0.5)
sns.regplot(x=df["Height"], y=df["Weight"], scatter=False, color="red")
plt.title("Height vs. Weight")
plt.xlabel("Height (cm)")
plt.ylabel("Weight (kg)")
plt.show()

# Compute the correlation matrix for numerical variables
correlation_matrix = df[["Age", "Height", "Weight", "Year"]].corr()

# Plot heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

"""Feature Selection"""

# Convert categorical variables into numerical values before correlation
from sklearn.preprocessing import LabelEncoder

categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = LabelEncoder().fit_transform(df[col])

# Plot heatmap
plt.figure(figsize=(12, 6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

"""MODEL DEVELOPMENT"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# Encode categorical target variable (Medal: Gold, Silver, Bronze -> 1, else 0)
df["Medal"] = df["Medal"].fillna("No Medal")  # Fill NaN values
label_encoder = LabelEncoder()
df["Medal_encoded"] = label_encoder.fit_transform(df["Medal"].astype(str))

# Selecting numerical features for correlation analysis
numeric_features = ["Age", "Height", "Weight", "Year"]
correlation_with_medal = df[numeric_features + ["Medal_encoded"]].corr()["Medal_encoded"].drop("Medal_encoded")

# Train a Random Forest model to get feature importance
X = df[numeric_features].dropna()  # Drop rows with missing values
y = df.loc[X.index, "Medal_encoded"]  # Ensure alignment

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X, y)

# Get feature importance scores
feature_importance = pd.Series(rf_model.feature_importances_, index=numeric_features)

correlation_with_medal, feature_importance

import pandas as pd

# Convert columns to numeric
df["Age"] = pd.to_numeric(df["Age"], errors='coerce')
df["Height"] = pd.to_numeric(df["Height"], errors='coerce')
df["Weight"] = pd.to_numeric(df["Weight"], errors='coerce')

# Fill missing values (optional, choose a method)
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Height"] = df["Height"].fillna(df["Height"].mean())
df["Weight"] = df["Weight"].fillna(df["Weight"].mean())

# Verify if all columns are now numeric
print(df.dtypes)

"""Model Evaluation and Hyperparameter Tuning"""

# Sample a smaller subset (10,000 rows) to reduce memory usage
df_sample = df[numeric_features + ["Medal_encoded"]].dropna().sample(n=10000, random_state=42)

# Prepare features and target variable
X_sample = df_sample[numeric_features]
y_sample = df_sample["Medal_encoded"]

# Train a smaller Random Forest model
rf_model_sample = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model_sample.fit(X_sample, y_sample)

# Get feature importance scores
feature_importance_sample = pd.Series(rf_model_sample.feature_importances_, index=numeric_features)

feature_importance_sample

# Sample a smaller subset (10,000 rows) to reduce memory usage
df_sample = df[numeric_features + ["Medal_encoded"]].dropna().sample(n=10000, random_state=42)

# Prepare features and target variable
X_sample = df_sample[numeric_features]
y_sample = df_sample["Medal_encoded"]

# Train a smaller Random Forest model
rf_model_sample = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model_sample.fit(X_sample, y_sample)

# Get feature importance scores
feature_importance_sample = pd.Series(rf_model_sample.feature_importances_, index=numeric_features)

feature_importance_sample

pip install imbalanced-learn

print(df["Medal"].value_counts())  # Check if both 0 and 1 exist

from sklearn.model_selection import train_test_split

# Assuming 'df' is your dataset and 'Medal' is the target column
X = df.drop(columns=['Medal'])  # Independent variables
y = df['Medal']  # Dependent variable (Target)

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Now you can print the class distribution
print("Training set class distribution:")
print(y_train.value_counts())

print("Testing set class distribution:")
print(y_test.value_counts())

y.value_counts()

y_test

# Step 1: Import Libraries
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from imblearn.over_sampling import SMOTE  # Handle imbalance

# Step 2: Load Dataset
df = pd.read_csv("athlete_events.csv")

# Step 3: Data Preprocessing
df = df[["Age", "Height", "Weight", "Year", "Medal"]].dropna().copy()

# Convert "Medal" column to binary classification (1 = Won a Medal, 0 = No Medal)
df["Medal"] = df["Medal"].notna().astype(int)

# **Step 4: Ensure at least TWO classes exist**
if df["Medal"].nunique() < 2:
    print("⚠ Warning: Dataset contains only one class. Adding synthetic class 0 records.")

    # Add synthetic "no-medal" records (based on averages)
    new_rows = pd.DataFrame({
        'Age': [df['Age'].mean()] * 100,
        'Height': [df['Height'].mean()] * 100,
        'Weight': [df['Weight'].mean()] * 100,
        'Year': [df['Year'].mean()] * 100,
        'Medal': [0] * 100
    })

    df = pd.concat([df, new_rows], ignore_index=True)

# Step 5: Feature Scaling
X = df.drop(columns=["Medal"])
y = df["Medal"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 6: Balance the dataset using SMOTE
smote = SMOTE(random_state=42)
X_scaled, y = smote.fit_resample(X_scaled, y)

# Step 7: Split Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Step 8: Train Logistic Regression Model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

# **Save the trained model using pickle**
with open("logistic_model.pkl", "wb") as model_file:
    pickle.dump(log_reg, model_file)

# **Save the scaler**
with open("scaler.pkl", "wb") as scaler_file:
    pickle.dump(scaler, scaler_file)

# Step 9: Model Evaluation
y_pred = log_reg.predict(X_test)

print("\nModel Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print(f"Precision: {precision_score(y_test, y_pred, zero_division=1):.2f}")
print(f"Recall: {recall_score(y_test, y_pred, zero_division=1):.2f}")
print(f"F1-score: {f1_score(y_test, y_pred, zero_division=1):.2f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=1))

"""Model Evaluation and Hyperparameter Tuning"""

#import pickel
import pickle as pkl

pkl.dump(log_reg,open('model.pkl','wb'))
pkl.dump(scaler,open('scaler.pkl','wb'))

import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Assume X_train and y_train are already defined
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Save model & scaler
with open("model.pkl", "wb") as model_file:
    pickle.dump(model, model_file)

with open("scaler.pkl", "wb") as scaler_file:
    pickle.dump(scaler, scaler_file)

